#!/usr/bin/env python3
"""Regenerate every per-agent adapter file from the canonical skills/ directory.

The skills in skills/ are the single source of truth. Cursor, GitHub Copilot, Gemini CLI and
Windsurf each want the same knowledge in their own file format; rather than maintain four
hand-written copies that drift, this script generates them all.

Run it after changing any SKILL.md frontmatter, then commit the result:

    python3 tools/sync-adapters.py
    python3 tools/sync-adapters.py --check    # non-zero exit if regeneration would change files

The generated files intentionally contain only a *pointer* plus the trigger description --
never a copy of the skill body. That way the body lives in exactly one place and the adapters
cannot go stale in substance, only in wording.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
REPO_URL = "https://github.com/intel471/integrations-skills"

BANNER = "GENERATED by tools/sync-adapters.py from skills/ -- do not edit by hand."

# Globs that should trigger these skills in tools that support path-scoped attachment.
# Deliberately broad: integration code is not confined to predictable filenames.
TRIGGER_GLOBS = ["**/*.py", "**/*.js", "**/*.ts", "**/*.ps1", "**/*.yaml", "**/*.yml"]


def parse_frontmatter(path: Path) -> dict[str, str]:
    """Pull name/description out of a SKILL.md YAML frontmatter block.

    Hand-rolled rather than depending on PyYAML: the frontmatter is two flat string keys and
    this script should run with a bare interpreter in CI.
    """
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        raise SystemExit(f"{path.relative_to(ROOT)}: missing YAML frontmatter")

    fields: dict[str, str] = {}
    key = None
    for line in match.group(1).splitlines():
        kv = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$", line)
        if kv:
            key, value = kv.group(1), kv.group(2).strip()
            # Strip the block scalar indicators used by multi-line descriptions.
            fields[key] = "" if value in (">-", ">", "|", "|-") else value
        elif key and line.strip():
            fields[key] = (fields[key] + " " + line.strip()).strip()

    for required in ("name", "description"):
        if not fields.get(required):
            raise SystemExit(f"{path.relative_to(ROOT)}: frontmatter missing '{required}'")
    return fields


def discover() -> list[dict[str, str]]:
    skills = []
    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        meta = parse_frontmatter(skill_md)
        directory = skill_md.parent.name
        if meta["name"] != directory:
            raise SystemExit(
                f"skills/{directory}/SKILL.md: frontmatter name '{meta['name']}' "
                f"does not match its directory name"
            )
        meta["path"] = f"skills/{directory}/SKILL.md"
        skills.append(meta)
    if not skills:
        raise SystemExit("no skills found under skills/*/SKILL.md")
    return skills


def render_cursor(skill: dict[str, str]) -> tuple[str, str]:
    globs = ", ".join(TRIGGER_GLOBS)
    body = f"""---
description: {skill['description']}
globs: {globs}
alwaysApply: false
---

<!-- {BANNER} -->

# {skill['name']}

Read [`{skill['path']}`]({REPO_URL}/blob/main/{skill['path']}) before writing or changing
code that calls the Intel 471 Titan or Verity471 APIs.

{skill['description']}

The skill file is a short index; open only the `references/` file for the topic at hand.
"""
    return f".cursor/rules/{skill['name']}.mdc", body


def render_copilot(skill: dict[str, str]) -> tuple[str, str]:
    body = f"""---
applyTo: "{','.join(TRIGGER_GLOBS)}"
description: {skill['description']}
---

<!-- {BANNER} -->

# {skill['name']}

When working on code that calls the Intel 471 Titan or Verity471 APIs, follow
[`{skill['path']}`]({REPO_URL}/blob/main/{skill['path']}).

{skill['description']}

The skill file is a short index; open only the `references/` file for the topic at hand.
"""
    return f".github/instructions/{skill['name']}.instructions.md", body


def render_windsurf(skill: dict[str, str]) -> tuple[str, str]:
    body = f"""---
trigger: glob
globs: {','.join(TRIGGER_GLOBS)}
description: {skill['description']}
---

<!-- {BANNER} -->

# {skill['name']}

Read [`{skill['path']}`]({REPO_URL}/blob/main/{skill['path']}) before writing or changing
code that calls the Intel 471 Titan or Verity471 APIs.

{skill['description']}
"""
    return f".windsurf/rules/{skill['name']}.md", body


def render_index(
    skills: list[dict[str, str]], title: str, preamble: str, prefix: str = ""
) -> str:
    """Render a repo-wide index file.

    `prefix` is prepended to every relative link, so a file written into a subdirectory
    (e.g. .github/copilot-instructions.md) still points at the repo root correctly.
    """
    rows = "\n".join(
        f"- **[`{s['path']}`]({prefix}{s['path']})** — {s['description']}" for s in skills
    )
    return f"""<!-- {BANNER} -->

# {title}

{preamble}

{rows}

Each skill is a lean index plus a `references/` directory. Read the index first, then open
only the reference file for the topic at hand.

Full detail, including the five highest-damage traps, is in [AGENTS.md]({prefix}AGENTS.md).
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any generated file is out of date (for CI)",
    )
    args = parser.parse_args()

    skills = discover()
    outputs: dict[str, str] = {}

    for skill in skills:
        for render in (render_cursor, render_copilot, render_windsurf):
            rel, body = render(skill)
            outputs[rel] = body

    preamble = (
        "This project follows the Intel 471 integration skills — patterns and traps for "
        "building against the Titan and Verity471 APIs. Consult the relevant skill before "
        "writing pagination, auth, or scheduled-connector logic."
    )
    outputs[".github/copilot-instructions.md"] = render_index(
        skills, "Intel 471 integration skills", preamble, prefix="../"
    )
    outputs["GEMINI.md"] = render_index(skills, "Intel 471 integration skills", preamble)

    stale = []
    for rel, body in sorted(outputs.items()):
        target = ROOT / rel
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current == body:
            continue
        stale.append(rel)
        if not args.check:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body, encoding="utf-8")

    if args.check:
        if stale:
            print("Adapters are out of date; run: python3 tools/sync-adapters.py")
            for rel in stale:
                print(f"  {rel}")
            return 1
        print(f"Adapters up to date ({len(outputs)} files, {len(skills)} skills).")
        return 0

    verb = "Updated" if stale else "Already current"
    print(f"{verb}: {len(stale) or len(outputs)} of {len(outputs)} files from {len(skills)} skills.")
    for rel in stale:
        print(f"  wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
